@echo off
echo "1"
OopLab1Var3.exe input.txt "output1_true.txt" "ma" "mama"
echo "2"
OopLab1Var3.exe input.txt "output2_true.txt" "1231234" "Ferrari"
echo "3"
OopLab1Var3.exe input.txt "output3_true.txt" "Alexander" "ASDABSJDGABSJDGBASBDJBASDHBKAHSBDHBASDBAKHSDBHASBHDKASBHDBHJASBHDASBHDABJHSDBHASDASDASDASDASDASDASDASDASDASDASDASDGASGDGASDVGASGDVDJVHAGSDVASDASDGHASHGDAGVSDGHSADASGHDGHASDGHASGHDASGVD"
echo "4"
OopLab1Var3.exe input.txt "output4_false.txt" "he"
echo "5"
OopLab1Var3.exe input.txt "output5_false.txt" "ma" "mama" "guchi"
echo "6"
OopLab1Var3.exe noSeachFile.txt "output6_false.txt" "false" "true"
echo "7"
OopLab1Var3.exe input.txt "output7_false.txt" "" "empty_search"
echo "8"
OopLab1Var3.exe input.txt "output8_true.txt" "ребенок"  
echo "9"
OopLab1Var3.exe input2Gb.txt "output9_false.txt" "ребенок" ""
pause