@echo off
echo "1"
OopLab1Var3.exe "input.txt" "output1True.txt" "ma" "mama"
echo "2"
OopLab1Var3.exe "input.txt" "output2True.txt" "1231234" "Ferrari"
echo "3"
OopLab1Var3.exe "input.txt" "output3True.txt" "Alexander" "ASDASASDABSJDGABSJDGBASBDJBASDHBKAHSBDHBASDBAKHSDBHASBHDKASBHDBHJASBHDASBHDABJHSDBHAASDABSJDGABSJDGBASBDJBASDHBKAHSBDHBASDBAKHSDBHASBHDKASBHDBHJASBHDASBHDABJHSDBHAASDABSJDGABSJDGBASBDJBASDHBKAHSBDHBASDBAKHSDBHASBHDKASBHDBHJASBHDASBHDABJHSDBHAASDABSJDGABSJDGBASBDJBASDHBKAHSBDHBASDBAKHSDBHASBHDKASBHDBHJASBHDASBHDABJHSDBHADASDAHGDAGVSDGHSADASGHDGHASDGHASSDASASGHDGHASDGHASSDASDASDASDASDHASHGDAGVS"
echo "4"
OopLab1Var3.exe "input.txt" "output4False.txt" "he"
echo "5"
OopLab1Var3.exe "input.txt" "output5False.txt" "ma" "mama" "guchi"
echo "6"
OopLab1Var3.exe "noSeachFile.txt" "output6False.txt" "false" "true"
echo "7"
OopLab1Var3.exe "input.txt" "output7True.txt" "" "empty_search"
echo "8"
OopLab1Var3.exe "input.txt" "output8True.txt" "Gen" ""
echo "9"
OopLab1Var3.exe "input2Gb.txt" "output9False.txt" "Gen" ""
pause